export const projects = [

    {
        id: 1,
        name: 'Tatry Razem',
        description: '(Application under construction).',
        type: "Web Applications",
        tags: [
            'Next.js',
            'Redux',
            'Typescript',
            'Supabase',
            'Git',
            'Tanstack-query',
        ],
        thumbnaill: 'https://jeiqdktodpczzgzkiocp.supabase.co/storage/v1/object/public/Portfolio/YCM.png',
        liveUrl: 'https://ycm-orcin.vercel.app/',
        codeUrl: '',
        APIlink: '',
    },

    {
        id: 2,
        name: 'Trek-Shop',
        type: "Web Applications",
        description: 'Trek Shop is an online store that relies on its own API written in Node.js and hosted online, making it accessible to users. This project was created with outdoor enthusiasts in mind, offering a rich variety of products, including climbing equipment, outdoor clothing, and more.',
        tags: [
            'React',
            'Redux',
            'Typescript',
            'Styled-components',
            'Git',
            'Tanstack-query',
        ],
        image: 'https://jeiqdktodpczzgzkiocp.supabase.co/storage/v1/object/public/Portfolio/TrekShop.png',
        liveUrl: 'https://mizdebski77.github.io/Trek-Shop/',
        codeUrl: 'https://github.com/mizdebski77/Trek-Shop',
        APIlink: 'https://trek-shop-database.onrender.com/',
    },

    {
        id: 3,
        name: 'Easy-Employ',
        type: "Web Applications",
        description: 'Easy Employ is a portal dedicated to employers and those looking for a job. Application under construction.',
        tags: [
            'React',
            'Typescript',
            'Redux',
            'Styled-components',
            'Git',
            'Tanstack-query',
        ],
        image: 'https://jeiqdktodpczzgzkiocp.supabase.co/storage/v1/object/public/Portfolio/EasyEmploy.png',
        liveUrl: 'https://mizdebski77.github.io/Easy-Employ/',
        codeUrl: 'https://github.com/mizdebski77/Easy-Employ',
        APIlink: 'https://esay-employ-database-wfsz.onrender.com/',
    },

    {
        id: 4,
        name: 'Movie Browser',
        type: "Web Applications",
        description: 'The Movies Browser is a platform you can easily search for your favorite movies, popular actors and actresses. Also you can find more information about the cast.',
        tags: [
            'React',
            'Redux',
            'Redux-saga',
            'Javascript',
            'Styled-components',
            'Git',
        ],
        image: 'https://jeiqdktodpczzgzkiocp.supabase.co/storage/v1/object/public/Portfolio/MovieBorwser.png',
        liveUrl: 'https://mizdebski77.github.io/Movie-Browser/',
        codeUrl: 'https://github.com/mizdebski77/Movie-Browser',
        APIlink: 'https://developer.themoviedb.org/docs/getting-started',
    },

    {
        id: 7,
        name: 'Wheather App',
        type: "Web Applications",
        description: 'The weather app is a one-page application that allows you to check the current weather in any city on earth. The app fetches data from "https://www.weatherapi.com/".',
        tags: [
            'React',
            'Redux',
            'Javascript',
            'Styled-components',
            'Git',
            'Redux-saga',
        ],
        image: 'https://jeiqdktodpczzgzkiocp.supabase.co/storage/v1/object/public/Portfolio/WeatherApp.png',
        liveUrl: 'https://mizdebski77.github.io/Weather-React-Redux-App/',
        codeUrl: 'https://github.com/mizdebski77/Weather-React-Redux-App',
        APIlink: 'https://www.weatherapi.com/',
    },

    {
        id: 8,
        name: 'Crud App',
        type: "Web Applications",
        description: 'The application was developed as per the directive from Futurum Technology. Throughout the project, I collaborated with a seasoned Figma designer and a proficient backend developer. The link provided showcases the basic version of the application, as the complete version was exclusively delivered to the company. The purpose of the app is to demonstrate the ability to develop a CRUD (Create, Read, Update, Delete) application for campaign management.',
        tags: [
            'Angular',
            'Scss',
            'Javascript',
            'Html',
            'Git',
        ],
        image: 'https://jeiqdktodpczzgzkiocp.supabase.co/storage/v1/object/public/Portfolio/Crud.png',
        liveUrl: 'https://crudaplication.netlify.app/',
        codeUrl: '',
        APIlink: '',
    },

    {
        id: 9,
        name: 'To do app',
        type: "Web Applications",
        description: '"To do list" is a web application which allows you to create a list of tasks that need to be done in the near future. At the top of application you can see a navigation toolbar which can take you to tasks page or to an author page.',
        tags: [
            'React',
            'Styled-components',
            'Redux',
            'Redux saga',
            'Git',
        ],
        image: 'https://jeiqdktodpczzgzkiocp.supabase.co/storage/v1/object/public/Portfolio/tasksList.png',
        liveUrl: 'https://mizdebski77.github.io/Tasks-List-ReactJS/',
        codeUrl: 'https://github.com/mizdebski77/Tasks-List-ReactJS',
        APIlink: '',
    },

    {
        id: 10,
        name: 'Dish Form',
        type: "Web Applications",
        description: 'Dish Form is a simple project that enables users to upload information about specific dishes to a website. The form includes fields such as dish name, preparation time, dish type (pizza, soup, or sandwich to choose from), as well as details depending on the selected type, such as the number of slices, diameter, spiciness , or number of bread slices',
        tags: [
            'React',
            'Styled-components',
            'Redux',
            'Html & Css',
            'Git',
        ],
        image: 'https://jeiqdktodpczzgzkiocp.supabase.co/storage/v1/object/public/Portfolio/Dish%20form.png',
        liveUrl: 'https://mizdebski77.github.io/Dish-Form/',
        codeUrl: 'https://github.com/mizdebski77/Dish-Form?tab=readme-ov-file',
        APIlink: '',
    },

    {
        id: 12,
        name: 'Think1st training app',
        type: "Web Applications",
        description: 'The training application was developed exclusively for Think1st, with this being a demo version as the full version was tailored specifically for the company`s needs. Throughout the project, I collaborated closely with a seasoned Figma designer and an expert backend developer. This project is a web application designed to facilitate sign-ups for training sessions. Users can provide necessary information such as their name, surname, email address, and photo, and select a training day and time. The application also fetches holiday data from the Ninja API to exclude Sundays and public holidays as training days, marking them as unavailable for selection and providing information about the holidays next to their names.',
        tags: [
            'React',
            'Tailwind css',
            'Tanstack query',
            'Api',
            'Git',
        ],
        image: 'https://jeiqdktodpczzgzkiocp.supabase.co/storage/v1/object/public/Portfolio/ta.png',
        liveUrl: 'https://mizdebski77.github.io/Training-App/',
        codeUrl: '',
        APIlink: '',
    },
]
